POST http://localhost:3000/api/shifts/create
Content-Type: application/json

  {
    "employee": "1",
    "date": "1531463770594",
    "location": "Springvale",
    "startTime": "2000",
    "endTime": "2000",
    "standardMinutes": "120",
    "overtimeMinutes": "60",
    "doubleTimeMinutes": "60",
    "totalPay": "2000"
  }

###
GET http://localhost:3000/api/shifts/

###
POST http://localhost:3000/api/employees/create/
Content-Type: application/json

  {
    "firstName": "Melisa",
    "lastName": "Mallard",
    "email": "ilikeducks@gmail.com",
    "password": "quackquack", 
    "location": "Highvale", 
    "standardRate": "22000"
  }

###
GET http://localhost:3000/api/employees/

###
PUT http://localhost:3000/api/employees/5b4c00915fc8d6039f43ab15
Content-Type: application/json

  {
    "firstName": "LOL",
    "lastName": "Jokes",
    "email": "ilikesalads@gmail.com",
    "password": "quackquack", 
    "location": "Highvale", 
    "standardRate": "22000"
  }


###
DELETE http://localhost:3000/api/employees/5b4d314d23058f00e8e089c8
Content-Type: application/json

###
GET http://localhost:3000/api/employees/5b4d3113057a6800db470245