###
POST http://localhost:3000/auth/employee/login
content-type: application/json
// Login. Notice that a valid token is recieved in the response header if the right details are provided.

{
  "email": "steve@redrocks.com",
  "password": "password"
}

###
POST http://localhost:3000/auth/employee/logout
content-type: application/json

###
POST http://localhost:3000/auth/employee/test
content-type: application/json
// Test to see if the cookie got deleted. If it got deleted, it should send back an empty object

###
POST http://localhost:3000/auth/employee/forgotPassword
content-type: application/json  
// Test to see if the cookie got deleted. If it got deleted, it should send back an empty object

###
PUT http://localhost:3000/auth/employee/updatePassword
content-type: application/json
// Test to see if the cookie got deleted. If it got deleted, it should send back an empty object

{
  "oldPassword": "password",
  "newPassword": "password123"
}